import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  pt: {
    translation: {
      settings: "Painel de Configurações",
      account: "Conta",
      newPassword: "Nova senha",
      changePassword: "Alterar Senha",
      login: "Login",
      updateProfile: "Atualizar Perfil",
      language: "Idioma",
      languageChanged: "Idioma alterado com sucesso!",
      errorChangePassword: "Erro ao alterar senha",
      errorUpdateProfile: "Erro ao atualizar perfil",
      errorChangeLanguage: "Erro ao mudar idioma",
      fontPreferences: "Preferências de Fonte",
      fontSize: "Tamanho da Fonte",
      fontType: "Tipo de Fonte",
      previewText: "Exemplo de texto com {{size}}px em {{font}}",

      home: "Home",
      myNotes: "Minhas Notas",
      darkMode: "Escuro",
      logout: "Sair",

      homeTitle: "Minhas Notas",
      searchNote: "Buscar nota...",
      notesCountSingular: "nota",
      notesCountPlural: "notas",
      noNotesFound: "Nenhuma nota encontrada",
      noNotesYet: "Nenhuma nota ainda",
      tryOtherFilters: "Tente outros termos.",
      createFirstNote: "Crie sua primeira nota para começar.",
      clearFilters: "Limpar filtros",

      mural: "Mural",
      addNote: "Adicionar Nota",
      save: "Salvar",
      cancel: "Cancelar",
      delete: "Excluir",
      edit: "Editar",
      emptyTextAlert: "O campo de texto não pode estar vazio!",

      email: "E-mail",
      senha: "Senha",
      entrar: "Entrar",
      error: "Erro",
      emailRequired: "O campo de e-mail é obrigatório.",
      invalidEmail: "Digite um e-mail válido (precisa conter @).",
      passwordRequired: "A senha é obrigatória.",
      missingTokenOrId: "Token ou ID não retornados pelo servidor.",
      loginFailed: "Não foi possível realizar o login.",

      noteNotFound: "Nota não encontrada",
      backToHome: "Voltar para Home",
      back: "Voltar",
      copied: "Copiado",
      copiedToClipboard: "Conteúdo copiado para a área de transferência!",
      noTitle: "(sem título)",
      addedOn: "Adicionado em",
      noContent: "Sem conteúdo.",
      copy: "Copiar",
      share: "Compartilhar",
      shareError: "Não foi possível compartilhar",

      chooseColor: "Escolha a cor:",
      yellow: "Amarelo",
      green: "Verde",
      blue: "Azul",
      pink: "Rosa",
      red: "Vermelho",
      orange: "Laranja",
      purple: "Roxo",
      gray: "Cinza",
      black: "Preto",
      white: "Branco"
    }
  },
  en: {
    translation: {
      settings: "Settings Panel",
      account: "Account",
      newPassword: "New password",
      changePassword: "Change Password",
      login: "Login",
      updateProfile: "Update Profile",
      language: "Language",
      languageChanged: "Language changed successfully!",
      errorChangePassword: "Error changing password",
      errorUpdateProfile: "Error updating profile",
      errorChangeLanguage: "Error changing language",
      fontPreferences: "Font Preferences",
      fontSize: "Font Size",
      fontType: "Font Type",
      previewText: "Sample text with {{size}}px in {{font}}",

      home: "Home",
      myNotes: "My Notes",
      darkMode: "Dark",
      logout: "Logout",

      homeTitle: "My Notes",
      searchNote: "Search note...",
      notesCountSingular: "note",
      notesCountPlural: "notes",
      noNotesFound: "No notes found",
      noNotesYet: "No notes yet",
      tryOtherFilters: "Try other terms.",
      createFirstNote: "Create your first note to start.",
      clearFilters: "Clear filters",

      mural: "Board",
      addNote: "Add Note",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      emptyTextAlert: "Text field cannot be empty!",

      email: "Email",
      senha: "Password",
      entrar: "Enter",
      error: "Error",
      emailRequired: "Email is required.",
      invalidEmail: "Enter a valid email (must contain @).",
      passwordRequired: "Password is required.",
      missingTokenOrId: "Token or ID not returned by server.",
      loginFailed: "Login failed.",

      noteNotFound: "Note not found",
      backToHome: "Back to Home",
      back: "Back",
      copied: "Copied",
      copiedToClipboard: "Content copied to clipboard!",
      noTitle: "(no title)",
      addedOn: "Added on",
      noContent: "No content.",
      copy: "Copy",
      share: "Share",
      shareError: "Unable to share",

      chooseColor: "Choose a color:",
      yellow: "Yellow",
      green: "Green",
      blue: "Blue",
      pink: "Pink",
      red: "Red",
      orange: "Orange",
      purple: "Purple",
      gray: "Gray",
      black: "Black",
      white: "White"
    }
  },
  es: {
    translation: {
      settings: "Panel de Configuración",
      account: "Cuenta",
      newPassword: "Nueva contraseña",
      changePassword: "Cambiar contraseña",
      login: "Usuario",
      updateProfile: "Actualizar perfil",
      language: "Idioma",
      languageChanged: "¡Idioma cambiado con éxito!",
      errorChangePassword: "Error al cambiar la contraseña",
      errorUpdateProfile: "Error al actualizar el perfil",
      errorChangeLanguage: "Error al cambiar el idioma",
      fontPreferences: "Preferencias de Fuente",
      fontSize: "Tamaño de Fuente",
      fontType: "Tipo de Fuente",
      previewText: "Ejemplo de texto con {{size}}px en {{font}}",

      home: "Inicio",
      myNotes: "Mis Notas",
      darkMode: "Oscuro",
      logout: "Salir",

      homeTitle: "Mis Notas",
      searchNote: "Buscar nota...",
      notesCountSingular: "nota",
      notesCountPlural: "notas",
      noNotesFound: "No se encontraron notas",
      noNotesYet: "Todavía no hay notas",
      tryOtherFilters: "Prueba otros términos.",
      createFirstNote: "Crea tu primera nota para empezar.",
      clearFilters: "Limpiar filtros",

      mural: "Muro",
      addNote: "Agregar Nota",
      save: "Guardar",
      cancel: "Cancelar",
      delete: "Eliminar",
      edit: "Editar",
      emptyTextAlert: "¡El campo de texto no puede estar vacío!",

      email: "Correo electrónico",
      senha: "Contraseña",
      entrar: "Iniciar sesión",
      error: "Error",
      emailRequired: "El campo de correo electrónico es obligatorio.",
      invalidEmail: "Ingrese un correo válido (debe contener @).",
      passwordRequired: "La contraseña es obligatoria.",
      missingTokenOrId: "Token o ID no devueltos por el servidor.",
      loginFailed: "No se pudo iniciar sesión.",

      noteNotFound: "Nota no encontrada",
      backToHome: "Volver al inicio",
      back: "Volver",
      copied: "Copiado",
      copiedToClipboard: "¡Contenido copiado al portapapeles!",
      noTitle: "(sin título)",
      addedOn: "Agregado en",
      noContent: "Sin contenido.",
      copy: "Copiar",
      share: "Compartir",
      shareError: "No se pudo compartir",

      chooseColor: "Elige un color:",
      yellow: "Amarillo",
      green: "Verde",
      blue: "Azul",
      pink: "Rosa",
      red: "Rojo",
      orange: "Naranja",
      purple: "Morado",
      gray: "Gris",
      black: "Negro",
      white: "Blanco"
    }
  }
};

i18n.use(initReactI18next).init({
  resources,
  lng: "pt",
  fallbackLng: "en",
  interpolation: { escapeValue: false }
});

export default i18n;
